DOGRU_SR_TEXT = ["Telefonunda en son aradığın şey neydi?","Birisi kız arkadaşın / erkek arkadaşından ayrılmak için sana 1 milyon tl önerseydi, yapar mıydın?",
				 "Bu grupda en az kimi seviyorsun ve neden?","Hiç sınıfta yüksek sesle geğirdin mi?",
				 "Hiç sınıfta yüksek sesle geğirdin mi?","Yerden bir şeyi alıp hiç yedin mi?",
				 "Bir gün karşı cins olarak uyanırsan, ilk yapacağın şey nedir?",
				 "Hiç havuzda işedin mi?","Asansörde hiç gaz kaçırdın mı?",
				 "Tuvalette otururken aklınıza gelen şeyler nelerdir?","Büyüyen hayali bir arkadaşınız var mıydı?",
				 "En kötü alışkanlığınız nedir?","Burnunu karıştırır mısın?","Banyoda şarkı söyler misin?",
				 "Hiç üzerine işedin mi?","Toplumda en utanç verici anınız neydi?","Aynada kendinle hiç konuştun mu?",
				 "Web geçmişinizi, birileri görürse utanacağınız şey ne olurdu?","Uykunda konuşur musun?",
				 "Gizli aşkın kim?","Benim hakkımda neyi sevmiyorsun?","Şu an ne renk iç çamaşır giyiyorsun?",
				 "Son attığın mesaj neydi?","İnsanları yanan bir binadan kurtarıyor olsaydınız ve bir kişiyi bu grupdan geride bırakmak zorunda kalırsanız, kim olurdu?",
				 "İç çamaşırlarını ne sıklıkla yıkıyorsun?","Hiç kulak kiri tattın mı?",
				 "Hiç osurup başka birini suçladın mı?","Hiç terinin tadına baktın mı?",
				 "Bu odadaki kim bugüne kadarki en kötü insan olurdu? Neden?",
				 "Yeniden doğmuş olsaydın, hangi yüz yılda doğmak isterdin?","Söylediğiniz veya yaptığınız bir şeyi silmek için zamanda geriye gidebilseydiniz, bu hangi yıl olurdu?",
				 "Erkek arkadaşın veya kız arkadaşın seni hiç utandırdı mı?","Birdenbire görünmez olsaydın ne yapardın?",
				 "Banyoda kaldığınız en uzun süre nedir ve neden bu kadar uzun süre kaldınız?","Şimdiye kadar gördüğüm en garip rüyayı anlat.",
				 "Duşta işiyor musun?","Hala yaptığın en çocukça şey nedir?","Hangi çocuk filmini tekrar tekrar izleyebilirsin?",
				 "Ayak kokunuz kötü mü?","Saçma takma adların var mı?","Telefonunuzda hangi uygulamada en çok zaman harcıyorsunuz?",
				 "Tek bir oturuşta yediğin en çok yemek ne?","Tek başınayken dans ediyor musun?","Karanlıktan korkar mısın?",
				 "Bütün gün evdeysen ne yapardın?","Günde kaç öz çekim yapıyorsunuz?","En son ne zaman dişlerini fırçaladın?",
				 "En sevdiğin pijamalar neye benziyor?","Hiç yerden bir şey yedin mi?","Yapmaman gereken bir şeyi yaparken hiç yakalandın mı?",
				 "Vücudunun hangi bölümünü seviyorsun, hangi kısmından nefret ediyorsun?","Hiç bitlendin mi?",
				 "Pantolonunu hiç kestin mi?","Tabağını yalıyor musun?","Kimsenin senin hakkında bilmediği bir şey nedir?",
				 "Hiç tabağını yaladın mı?","Dirseğini yalayabilir misin?","Eğer buradaki herkesi yanan bir binadan kurtarmaya çalışıyor olsaydın ve birini geride bırakmak zorunda kalırsan, kimi geride bırakırdın?",
				 "Telefonda aradığın son şey neydi?","Bir uygulamayı telefonunuzdan silmek zorunda kalsanız hangisini silerdiniz?","Bir ilişkideki en büyük korkun nedir?",
				 "Odanın her bir kişi hakkında bir tane olumlu, bir tane olumsuz şey söyleyin.","Sevmediğin kötü huyun var mı?",
				 "Hayatında yaptığın en çılgın şey nedir?","Üç gün boyunca bir adada mahsur kalmış olsaydınız, bu grupdan kimleri seçerdiniz?",
				 "Bu odadaki en sinir bozucu kişi kim?","Bu grupdan biriyle evlenmek zorunda kalsan kim olurdu?","En uzun ilişkiniz ne kadar sürdü?",
				 "Bir ünlü Instagram’da seni takip etseydi bu ünlünün kim olmasını isterdin?","Instagram’da 5 kişiyi silmek zorunda olsan kimleri silerdin?",
				 "Kaç çocuk sahibi olmak istersin?","Hayallerinizdeki kişiyi tarif edin.","Messi mi Ronaldo mu?","Pes mi Fifa mı?",
				 "İlk işin neydi?","Üniversite hakkındaki en büyük korkun nedir?","En iyi arkadaşının seninle aynı üniversiteye gitmesini ister misin?",
				 "Mevcut erkek arkadaşının ya da kız arkadaşının seninle aynı üniversiteye gitmesini ister misin?","Hayalindeki iş ne?",
				 "Hiç bir dersten başarısız oldun mu?","Hiç kopya çektin mi?","Hiç sınıfta uyudun mu?","Sınıfta asla yanında oturmak istemeyeceğin kim?",
				 "Derse hiç geç kaldın mı?","Bir öğretmenin önünde yaptığın en utanç verici şey nedir?","Hiç masanın altına sakız attın mı?",
				 "Hiç okulda kavga ettin mi?","Bir sınavdan aldığın en kötü puan neydi?","Sınıfta hiç uyuya kaldın mı?","Hiç gözaltına alındın mı?",
				 "Eğer görünmez olsaydın hangi derse gizlice girerdin?","En kötü grup hangisidir?","Bu grupdaki sır tutma  konusunda en çok zorlanan kişi kimdir?",
				 "Söylediğin en son yalan neydi?","Spor yapar mısın?","Hayatının geri kalanında sadece bir kıyafet giyebilseydin, bu kıyafetin hangi renk olurdu?",
				 "Sizce Türkiye’nin eğitim sisteminde yapılması gereken en önemli değişiklik nedir?","Karanlıktan/yükseklikten korkar mısın?",
				 "Kendi görünuşünü 1 ile 10 arasında puanla :)","Yaptıgın en yasadışı şey neydi?","Şimdi sana bir evlenme teklifi gelse ve sevmediğin biri olsa, ve bu sana son gelecek evlilik teklifi olsa kabul edermiydin?",
				 "Şu anki ruh haline bakarak ne tür film izlersin (aksiyon/dram/bilim kurgu/romantik komedi/biyografi/fantastik)"]
